services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "8085:80"
    environment:
      - TZ=Asia/Shanghai
      - SIGNUPS_ALLOWED=${VAULT_SIGNUPS_ALLOWED}
      - SIGNUPS_VERIFY=false
      - ADMIN_TOKEN=${VAULT_ADMIN_TOKEN}
      - DOMAIN=https://vault.${DOMAIN_EXTERNAL}
      - DISABLE_ICON_DOWNLOAD=false
    volumes:
      - /share/Container/vaultwarden/data:/data
