
services:
  traefik:
    image: traefik:v3.6
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=aijias-public"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/stunnel:/certs:ro
      - /File/Container/traefik/dynamic:/etc/traefik/dynamic
    networks:
      - aijias-public

  traefik-manager:
    image: ghcr.io/chr0nzz/traefik-manager:latest
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - TRAEFIK_API_URL=http://traefik:8080
      - CONFIG_DIR=/config
      - TZ=Asia/Shanghai
      # 管理员账号密码（admin / 请修改你的密码）
      - ADMIN_USER=louis
      - ADMIN_PASSWORD_HASH=$2y$10$XHxrPeSCmy6cj8sIybTGouGZ5L79FWQtstQtLqW5nOX7kwCZvty6u% 
    ports:
      - "8081:8081"
    volumes:
      - /File/Container/traefik/dynamic:/config
      - /File/Container/traefik/manager-db:/data
    networks:
      - aijias-public

networks:
  aijias-public:
    external: true

  aijias-internal:
    external: true
