homeassistant:
  name: 家
  latitude: 31.82
  longitude: 117.23
  unit_system: metric
  time_zone: Asia/Shanghai
  country: CN
  customize: !include customize.yaml

default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24

input_datetime: !include input_datetime.yaml
sensor: !include sensors.yaml
automation: !include automations.yaml

recorder:
  db_url: !secret recorder_db_url